#!/usr/bin/env python
# Copyright (c) 2012 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# A simple native messaging host. Shows a Tkinter dialog with incoming messages
# that also allows to send message back to the webapp.

import struct
import sys
import os

# Helper function that sends a message to the webapp.
def send_message(message):
   # Write message size.
  sys.stdout.write(struct.pack('I', len(message)))
  # Write the message itself.
  sys.stdout.write(message)
  sys.stdout.flush()

# Thread that reads messages from the webapp.
def read_thread_func(queue):
  message_number = 0
  brightnesscur = 0
  brightnessmax = 0
  ALSstatus = 0
  output = os.popen('cat /sys/class/backlight/backlight/brightness')
  brightnesscur = int (output.read())
  output = os.popen('cat /sys/class/backlight/backlight/max_brightness')
  brightnessmax = int (output.read())
  brightnesstmp = brightnesscur
  test = '"' + str(int(round(brightnesstmp) ))+ '"'
  send_message( test )
  while 1:
    # Read the message length (first 4 bytes).
    text_length_bytes = sys.stdin.read(4)

    if len(text_length_bytes) == 0:
      if queue:
        queue.put(None)
      sys.exit(0)

    # Unpack message length as 4 byte integer.
    text_length = struct.unpack('i', text_length_bytes)[0]

    # Read the text (JSON object) of the message.
    text = sys.stdin.read(text_length);
    textstr=text.strip('"')
    if queue:
      queue.put(text)
    else:
      # In headless mode just send an echo message back.
      #send_message(test)
      findret = textstr.find('ALSON')
      if findret > -1 :
        #brightnesscmd = "/usr/sbin/i2cset -y 2 0x66 1 1"
        #os.system(brightnesscmd )
        continue
      findret = textstr.find('ALSOFF')
      if findret > -1 :
        #brightnesscmd = "/usr/sbin/i2cset -y 2 0x66 1 0"
        #os.system(brightnesscmd )
        continue
      #brightnesscur =int(round(float(textstr) * brightnessmax /100))
      brightnesscur =int(round(float(textstr)))
      if brightnesscur > 0 and brightnesscur <=brightnessmax :
        brightnesscmd = "echo " + str(brightnesscur ) + " > /etc/brightness"
        os.system(brightnesscmd )
        brightnesscmd = "echo " + str(brightnesscur ) + " >/sys/class/backlight/backlight/brightness"
        os.system(brightnesscmd )
        brightnesstmp = int(brightnesscur)
        test = '"' + str(int(round(brightnesstmp) ))+ '"'
        send_message( test )
        test = '"' + "brightness" + str(int(round(brightnesstmp) ))+ '"'
        send_message( test )
      continue

def Main():
    read_thread_func(None)
    sys.exit(0)

if __name__ == '__main__':
  Main()
