#!/bin/sh

. /etc/formfactor/config

if [ "$HAVE_TOUCHSCREEN" = "1" ]; then
    SHOWCURSOR="no"
else
    SHOWCURSOR="yes"
fi

if [ "$HAVE_KEYBOARD" = "1" ]; then
    KEYBOARD_APPLET=""
else
    KEYBOARD_APPLET="keyboard"
fi

matchbox-desktop & 
sync
sleep 1

# Lines containing feature-[foo] are removed at build time if the machine
# doesn't have the feature "foo".

START_APPLETS=showdesktop,windowselector
END_APPLETS=clock,$KEYBOARD_APPLET,systray,startup-notify,notify

matchbox-panel --start-applets $START_APPLETS --end-applets $END_APPLETS &
sync
sleep 1

exec matchbox-window-manager -theme Sato -use_cursor $SHOWCURSOR $@
sync
sleep 2
